name: Unit Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: WJSoftware/cicd/.github/workflows/npm-test.yml@main
    with:
      node-version: 26
      build-script: build
      test-script: test
      build: true
